config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  resources :idioms do
    resources :comments
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  resources :users do
    resources :idioms, only: [:index]
  end
  resources :idioms do
    resources :likes
    resources :unlikes
  end

  ### Admin

  resources :admin, only: [:index]
  namespace :admin do
    root 'admin#index'
    resources :user
    resources :idiom
    resources :comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idiom
  belongs_to :user

  validates :body, presence: true, length: { minmum: 2, maximum: 100 }
  validates :user, presence: true
  validates :idiom, presence: true
end

app/models/idiom.rb
class Idiom < ApplicationRecord
  before_create :default_likes
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :unlikes, dependent: :destroy

  validates :title_en, presence: true, length: { minimum: 2, maximum: 50 }
  validates :title_fr, presence: true, length: { minimum: 2, maximum: 50 }
  validates :grammatical_type, presence: true
  validates :body, presence: true, length: { minimum: 15, maximum: 300 }
  validates :example_fr, presence: true, length: { minimum: 15, maximum: 200 }
  validates :example_en, presence: true, length: { minimum: 15, maximum: 200 }
  validates :user, presence: true

  def self.search_by(search)
    @all_letters = [*'A'..'Z']
    if search.blank?
      all
    elsif search == 'top'
      order('likes_count DESC')
    elsif @all_letters.include?(search)
      where('title_en ILIKE ?', "#{search}%")
    else
      where('title_en ILIKE ?', "%#{search}%")
    end
  end

  def default_likes
    self.likes_count = 0
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idiom, counter_cache: true
end

app/models/unlike.rb
class Unlike < ApplicationRecord
  belongs_to :idiom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  before_create :aliases_attribution
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_one_attached :avatar

  has_many :idioms, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :unlikes, dependent: :destroy

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def aliases_attribution
    num = rand(1..7)
    self.alias = "disrupt-#{SecureRandom.hex(2)}"
    avatar.attach(io: File.open(Rails.root.join("app/assets/images/avatar-#{num}.jpeg")),
                  filename: "avatar-#{num}.jpeg", content_type: 'image/jpeg')
  end

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def is_admin?
    self.admin?
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :check_if_admin

  def index
    @users = User.all
    @idioms = Idiom.all
    @comments = Comment.all
    @admin = current_user.admin
  end

  private

  def check_if_admin
    redirect_to idioms_path if current_user.admin == false
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_idiom
  before_action :find_like, only: [:destroy]

  def create
    if already_unliked?
      flash[:notice] = 'Une intéressante contradiction !'
    else
      @idiom.likes.create(user: current_user)
    end
    redirect_back(fallback_location: idioms_path)
  end

  def destroy
    @like.destroy
    redirect_back(fallback_location: idioms_path)
  end

  private

  def find_idiom
    @idiom = Idiom.find(params[:idiom_id])
  end

  def find_like
    @like = @idiom.likes.find(params[:id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!, :same_user?

  def show
    @likes = Like.where(user: @user)
    @idioms = Idiom.where(user: @user)
    @comments = Comment.where(user: @user)
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def same_user?
    @user = User.find(params[:id])
    current_user == @user ? nil : (redirect_to idioms_path)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_for_flash(type)
    case type
    when 'notice' then 'alert__info'
    when 'success' then 'alert__success'
    when 'error' then 'alert__danger'
    when 'alert' then 'alert__warning'
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  include Pagy::Frontend
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/idioms_helper.rb
module IdiomsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image'])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?('http') ? meta_image : image_url(meta_image)
  end
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/unlikes_helper.rb
module UnlikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="container">
    <h1>Tableau de bord Admininistrateur</h1>
    <%= link_to "Retourner à l'accueil", idioms_path, class: "button__normal button__success" %>
    <br>
    <h4><%= @users.all.count %> utilisateurs crées</h4>
    <%= link_to 'Gérer tous les utilisateurs', admin_user_index_path, class: "button__normal button__info" %>
    <hr>
    <h4><%= @idioms.all.count%> expressions proposées</h4>
    <h5><%= @idioms.where(validated: true).count%> validées || <%= @idioms.where(validated: false).count%> en cours de validation</h5>
    <%= link_to 'Gérer toutes les expressions', admin_idiom_index_path, class: "button__normal button__info" %>
    <hr>
    <h4><%= @comments.all.count %> commentaires crées</h4>
    <%= link_to 'Gérer tous les commentaires', admin_comment_index_path, class: "button__normal button__info" %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= class_for_flash(type) %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer center">
<%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar" id="burger__menu">
  <div class="navbar__top">
      <%= link_to idioms_path, class: 'navbar__top--logo', id: 'menu__logo'  do %>
        <%= image_tag "/logoslaf.png", id: "navbar__logo" %>
      <% end %>
      <div class="navbar__mobile--close" id="burger__button2">
        <%= render partial: "svgs/burger.html.erb" %>
      </div>
      <ul class="list__unstyled">
        <%= link_to "CRÉER UNE EXPRESSION", new_idiom_path, class: 'button__letter button__info', style: "margin-bottom: 15px;" %>

        <%= form_for "", url: idioms_path, role: "search", method: :get do%>
        <%= text_field_tag :search, @search, placeholder: "Rechercher", class: 'search__form--control'%>
        <%= button_tag(type: "submit", class: "button__search button__danger") do %>
          <%= render partial: "svgs/search.html.erb" %>
        <% end %>
        <% end%>
      <div class="navbar-browse">
        <span id="browse__button">Parcourir&nbsp;
        <%= render partial: "svgs/browse.html.erb" %>
        </span>
        <div class="row" id="letter__tags">
            <% @letters.first(6).each do |letter| %>
            <div class="col-2">
              <%= link_to letter, idioms_path(:search => letter), class: 'button__letter button__info' %>
            </div>
            <% end %>
            <div class="display__numbers" id="browse__list">
            <% @letters.last(20).each do |letter| %>
            <div class="col-2">
              <%= link_to letter, idioms_path(:search => letter), class: 'button__letter button__info' %>
            </div>
            <% end %>
            </div>
        </div>
      </div>
      <div class="navbar__buttons">
        <%= render 'application/random' %>
        <%= link_to "FLORILÈGE", idioms_path(:search => "top"), class: 'button__large button__success' %>
      </div>
    </div>
    <div class="navbar__bottom">
      <div class="navbar__bottom--left">
        <ul class="list__unstyled">
          <li><%= link_to "Accueil", root_path, class: 'nav-link' %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Profil", user_path(current_user.id), class: 'nav-link' %></li>
            <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete, class: 'nav-link' %></li>
            <%if current_user.admin == true%>
              <li><%=link_to "Panneau d'administration", admin_index_path, class: 'nav-link'%></li>
            <%end%>
          <% else %>
            <li><%= link_to "S'inscrire", new_user_registration_path, class: 'nav-link' %></li>
            <li><%= link_to "Se connecter", new_user_session_path, class: 'nav-link' %></li>
            <% end %>
        </ul>
      </div>
      <div class="navbar__logo">
        <div class="">

        <%= link_to "mailto:contact@syndicatdelutteantifranglais.club" do %>
          <%= render partial: "svgs/mail.html.erb" %>
        <% end %>
        <%= link_to "https://github.com/SLAF-Project/SLAF_Project" do %>
          <%= render partial: "svgs/github.html.erb" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_navbar_mobile.html.erb
<nav class="navbar__mobile">
	<div class="navbar__mobile--logo">
		<%= link_to root_path do %>
			<%= image_tag "/logoslaf.png", id: "navbar__mobile--img" %>
		<% end %>
		</div>
	<div class="navbar__mobile--burger" id="burger__button">
	<%= render partial: "svgs/burger-mobile.html.erb" %>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SLAF</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="google-site-verification" content="HDbFbQ8GAXvYh95JaT9Jko0fta3ZTcR-1EXlIabEkfU" />

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

  </head>
  <% unless action_name == "home" %>
  <%= render 'layouts/navbar'%>
  <% end %>
  <main>
    <% unless action_name == "home" %>
    <%= render 'layouts/navbar_mobile'%>
    <% end %>
    <div class="content">
      <%= render 'layouts/flash'%>
      <%= render "devise/shared/error_messages", resource: resource %>
      <%= yield %>
      <% unless action_name == "home" %>
      <%= render 'layouts/footer' if @pagy != nil %>
      <% end %>
    </div>
  </main>
  <%= javascript_include_tag "randombtn.js" %>
  <%= javascript_include_tag "burger" %>
  <%= javascript_include_tag "browse" %>
</html>

app/views/shared/_pagination.html.erb
link = pagy_link_proc(pagy)

%nav.pagy_nav.pagination{"aria-label" => "pager", :role => "navigation"}

  if pagy.prev
    %span.page.prev!= link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="précédent"')
  else
    %span.page.prev.disabled!= pagy_t('pagy.nav.prev')

  pagy.series.each do |item|       # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
    if item.is_a?(Integer)         # page link
      %span.page
        != link.call(item)

    elsif item.is_a?(String)       # current page
      %span.page.current= item

    elsif item == :gap             # page gap
      %span.page.gap!= pagy_t('pagy.nav.gap')

  if pagy.next
    %span.page.next!= link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="suivant"')
  else
    %span.page.next.disabled!= pagy_t('pagy.nav.next')

app/views/svgs/_browse.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16" id="browse__arrow">
  <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
</svg>

app/views/svgs/_burger-mobile.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
<path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
</svg>

app/views/svgs/_burger.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
<path fill-rule="evenodd" d="M13.854 2.146a.5.5 0 0 1 0 .708l-11 11a.5.5 0 0 1-.708-.708l11-11a.5.5 0 0 1 .708 0Z"/>
<path fill-rule="evenodd" d="M2.146 2.146a.5.5 0 0 0 0 .708l11 11a.5.5 0 0 0 .708-.708l-11-11a.5.5 0 0 0-.708 0Z"/>
</svg>

app/views/svgs/_github.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>

app/views/svgs/_like.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
<path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
</svg>

app/views/svgs/_liketwo.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
<path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
</svg>

app/views/svgs/_mail.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M0 3v18h24v-18h-24zm6.623 7.929l-4.623 5.712v-9.458l4.623 3.746zm-4.141-5.929h19.035l-9.517 7.713-9.518-7.713zm5.694 7.188l3.824 3.099 3.83-3.104 5.612 6.817h-18.779l5.513-6.812zm9.208-1.264l4.616-3.741v9.348l-4.616-5.607z"/></svg>

app/views/svgs/_search.html.erb
<svg class="w-6 h-6" fill="none" width="20" height="20" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>

app/views/svgs/_unlike.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-hand-thumbs-down-fill" viewBox="0 0 16 16">
<path d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.856 0-.29-.036-.586-.113-.857a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
</svg>

app/views/svgs/_unliketwo.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
<path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z"/>
</svg>