config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  resources :idioms do
    resources :comments
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  resources :users do
    resources :idioms, only: [:index]
  end
  resources :idioms do
    resources :likes
    resources :unlikes
  end

  ### Admin

  resources :admin, only: [:index]
  namespace :admin do
    root 'admin#index'
    resources :user
    resources :idiom
    resources :comment
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  before_create :aliases_attribution
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_one_attached :avatar

  has_many :idioms, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :unlikes, dependent: :destroy

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def aliases_attribution
    num = rand(1..7)
    self.alias = "disrupt-#{SecureRandom.hex(2)}"
    avatar.attach(io: File.open(Rails.root.join("app/assets/images/avatar-#{num}.jpeg")),
                  filename: "avatar-#{num}.jpeg", content_type: 'image/jpeg')
  end

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def is_admin?
    self.admin?
  end

end

app/controllers/admin/user_controller.rb
module Admin
  class UserController < ApplicationController
    def index
      @user = User.all.sort_by(&:created_at).reverse
    end

    def show
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      @user.update(admin: params[:submit])
      redirect_to admin_user_path(@user.id), success: 'Édition validée !'
    end

    def destroy
      User.find(params[:id]).destroy
      redirect_to admin_user_index_path
    end

    def edit
      @user = User.find(params[:id])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!, :same_user?

  def show
    @likes = Like.where(user: @user)
    @idioms = Idiom.where(user: @user)
    @comments = Comment.where(user: @user)
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def same_user?
    @user = User.find(params[:id])
    current_user == @user ? nil : (redirect_to idioms_path)
  end

end

app/helpers/admin/user_helper.rb
module Admin
  module UserHelper
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_cards.html.erb
<% @idioms.each do |idiom| %>
<div class="card">
        <% if idiom.validated == false %>
        <p><span class='status-tag-error'>En cours de validation</span></p>
        <%else%>
        <p><span class='status-tag-success'>Validée</span></p>
        <%end%>
    <div class="card__title">
        <span class="card__title--first"><%= idiom.title_en.capitalize %></span><%= idiom.grammatical_type.capitalize[0..2] %>.<br>
    </div>
    <div class="card__body">
        <span >Traduction</span> : <%= idiom.title_fr.capitalize %><br>
        <span >Définition</span> : <%=idiom.body%>
    </div>
    <div class="card__bottom">
        <div class="card__row">
            <%= idiom.likes.count %>
            <%= render partial: "svgs/liketwo.html.erb" %>
            </svg> <%= idiom.unlikes.count %>
            <%= render partial: "svgs/unliketwo.html.erb" %>
        </div>
        <div class="card__row">
            <%= link_to "VOIR", idiom_path(idiom.id), class: 'button__normal button__info' %>
        </div>
    </div>
</div>
<%end%>

app/views/users/_comment.html.erb
<% @comments.each do |comment| %>
<div class="card">
    <div class="card__title">
        <span class="card__title--first">"<%= comment.body %>"<br>
    </div>
    <div class="card__body">
            <span >Expression</span> : <%= comment.idiom.title_en.capitalize %><br>
    </div>
    <div class="card__bottom">
        <div class="card__row">
        </div>
        <div class="card__row">
    <%= link_to 'Voir', idiom_path(comment.idiom.id), class: 'button__normal button__info'%>
        </div>
    </div>
</div>
<%end%>

app/views/users/_likes.html.erb
<% @likes.each do |like| %>
<div class="card">
    <div class="card__title">
        <span class="card__title--first"><%= like.idiom.title_en.capitalize %></span><br>
    </div>
    <div class="card__body">
        <span>Traduction</span> : <%= like.idiom.title_fr.capitalize %><br>
    </div>
    <div class="card__bottom">
        <div class="card__row">
            <%= like.idiom.likes.count %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
              <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
            </svg> <%= like.idiom.unlikes.count %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
              <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z"/>
            </svg>
        </div>
        <div class="card__row">
            <%= link_to "VOIR", idiom_path(like.idiom.id), class: 'button__normal button__info' %>
        </div>
    </div>
</div>
<%end%>

app/views/users/_profile.html.erb
<div class="profile__content">
  <div class="profile__info row">
    <div class="profile-info-pic col-5">
    <div class='avatar'>
      <%if @user.avatar.attached?%>
        <%= image_tag @user.avatar, class: 'pic-avatar'%>
      <%else%>
        <p>Il n'y a pas encore d'avatar lié à cet utilisateur</p>
      <%end%>
    </div>
      <div class='form-picture'>
      <%= form_tag user_avatars_path(@user), multipart: true do %>
      <span class="button__normal button__info button__file">
        ÉDITER MON AVATAR
        <%= file_field_tag :avatar, class: 'button__normal button__info button__file' %>
      </span>
        <%= submit_tag "CHARGER", class: 'button__normal button__info' %>
      <% end %>
    </div>
  </div>
    <div class="profile-info-text col-7">
      <div class= "profile-info-text-elt">
        <span>Alias : </span><span style="font-weight: 700;"><%= @user.alias%></span>
      </div>
      <div class= "profile-info-text-elt">      
        <span>Prénom : </span><span style="font-weight: 700;"><%= @user.first_name%></span>
      </div>
      <div class= "profile-info-text-elt">
        <span>Nom : </span><span style="font-weight: 700;"><%= @user.last_name%></span>
      </div>
      <div class= "profile-info-text-elt">
        <span>Email : </span><span style="font-weight: 700;"><%= @user.email%></span>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile__title profile__title--bg-color-1">
  <h1>Mon profil</h1>
  <%= link_to "Editer", edit_user_registration_path, class: 'button__normal button__info' %>
</div>

<%= render 'profile'%>

  <div class="profile-my-idioms">
    <div class="profile__title profile__title--bg-color-2">
      <h2>Mes Expressions</h2>
    </div>
      <%= render 'cards' %>  
  </div>
    
  <div class="profile-my-likes">
      <div class="profile__title profile__title--bg-color-2">
        <h2>Mes Favoris</h2>
      </div>
  <%= render 'likes' %>
  </div>

    <div class="profile-my-likes">
      <div class="profile__title profile__title--bg-color-2">
        <h2>Mes commentaires</h2>
      </div>
  <%= render 'comment' %>
  </div>