config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  resources :idioms do
    resources :comments
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  resources :users do
    resources :idioms, only: [:index]
  end
  resources :idioms do
    resources :likes
    resources :unlikes
  end

  ### Admin

  resources :admin, only: [:index]
  namespace :admin do
    root 'admin#index'
    resources :user
    resources :idiom
    resources :comment
  end
end

app/models/idiom.rb
class Idiom < ApplicationRecord
  before_create :default_likes
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :unlikes, dependent: :destroy

  validates :title_en, presence: true, length: { minimum: 2, maximum: 50 }
  validates :title_fr, presence: true, length: { minimum: 2, maximum: 50 }
  validates :grammatical_type, presence: true
  validates :body, presence: true, length: { minimum: 15, maximum: 300 }
  validates :example_fr, presence: true, length: { minimum: 15, maximum: 200 }
  validates :example_en, presence: true, length: { minimum: 15, maximum: 200 }
  validates :user, presence: true

  def self.search_by(search)
    @all_letters = [*'A'..'Z']
    if search.blank?
      all
    elsif search == 'top'
      order('likes_count DESC')
    elsif @all_letters.include?(search)
      where('title_en ILIKE ?', "#{search}%")
    else
      where('title_en ILIKE ?', "%#{search}%")
    end
  end

  def default_likes
    self.likes_count = 0
  end
end

app/controllers/admin/idiom_controller.rb
module Admin
  class IdiomController < ApplicationController
    def show
      @idiom = Idiom.find(params[:id])
    end

    def index
      @idioms = Idiom.all.sort_by(&:created_at).reverse
    end

    def edit
      @idiom = Idiom.find(params[:id])
    end

    def update
      @idiom = Idiom.find(params[:id])
      @idiom.update(validated: params[:submit])
      redirect_to admin_idiom_index_path, success: 'Édition validé !'
    end

    def destroy
      Idiom.find(params[:id]).destroy
      redirect_to admin_idiom_index_path, success: 'Expression supprimée avec succès !'
    end
  end
end

app/controllers/idioms_controller.rb
class IdiomsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def show
    @idiom = Idiom.find(params[:id])
  end

def index
  @index_idioms = Idiom.where(validated: true)
  if params[:user_id].nil?
    @idioms_ = @index_idioms.search_by(params[:search])
  else
    @user = User.find(params[:user_id])
    @idioms_ = @index_idioms.where(user: @user)
  end
  @pagy, @idioms = pagy(@idioms_.order(created_at: :desc))
end

  def new
  end

  def create
    @idiom = Idiom.create(
      title_en: params[:idioms][:title_en],
      title_fr: params[:idioms][:title_fr],
      grammatical_type: params[:idioms][:grammatical_type],
      body: params[:idioms][:body],
      example_fr: params[:idioms][:example_fr],
      example_en: params[:idioms][:example_en],
      user: current_user
    )

    if @idiom.save
      flash[:success] = 'Ton expression est en cours de validation !'
      redirect_to idiom_path(@idiom.id)
    else
      flash.now[:error] = @idiom.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    if current_user.admin == true || current_user == @idiom.user
      @idiom = Idiom.find(params[:id])
    else
      redirect_to idiom_path
    end
  end

  def update
    @idiom = Idiom.find(params[:id])
    if @idiom.update(
      title_en: params[:idiom][:title_en],
      title_fr: params[:idiom][:title_fr],
      grammatical_type: params[:idiom][:grammatical_type],
      body: params[:idiom][:body],
      example_fr: params[:idiom][:example_fr],
      example_en: params[:idiom][:example_en],
      user: current_user
    )
      flash[:notice] = 'Édition réussie !'
      redirect_to idiom_path(@idiom.id)
    else
      flash.now[:error] = @idiom.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @idiom = Idiom.find(params[:id])
    @idiom.destroy
    redirect_back(fallback_location: idioms_path)
  end

end

app/helpers/admin/idiom_helper.rb
module Admin
  module IdiomHelper
  end
end

app/helpers/idioms_helper.rb
module IdiomsHelper
end

app/views/idioms/_cards.html.erb
<% @idioms.each do |idiom| %>
<div class="card">
    <div class="card__bottom">
        <div class="card__title">
        <div class="card__title--main"><b class="card__title--first show__links"><%= link_to "#{idiom.title_en.capitalize}", idiom_path(idiom.id), {:style=>'font-weight: 800;font-family: "Fraunces"'} %></b><span><%= idiom.grammatical_type.capitalize[0..2] %>.</div></span><span class="card__title--second" style="font-weight: 800; font-family: 'Fraunces'"><%= idiom.title_fr.capitalize %></span>
        </div>
        <div class="card__row--social" style="padding-right: 0.9vw;">
            <%= social_share_button_tag("On ne dit pas #{idiom.title_en} mais #{idiom.title_fr} ! Merci le @SLAF_FR") %>
        </div>
    </div>
    <div class="card__body">
        <p><%=idiom.body%><p>
        <i>"<%=idiom.example_en%>"</i>
        <p><i>"<%=idiom.example_fr%>"</i><p>

    </div>
    <div class="card__bottom">
        <div class="card__row">
            <%= render :partial => "like", :locals => { :idiom => idiom } %>
            <%= render :partial => "unlike", :locals => { :idiom => idiom } %>
        </div>
        <div class="card__row">
        <%= link_to "VOIR", idiom_path(idiom.id), class: 'button__normal button__info' %>
        </div>
    </div>
</div>
<%end%>

app/views/idioms/_comments_form.html.erb
<%= form_for(:comments, url:(idiom_comments_path(@idiom)), action: "create", method: :post) do |f| %>
<div class="card">
    
    <div>
    <%= f.text_area :body, class: "form__comment", placeholder: 'Ton commentaire (2 - 100 carac.)' %>
    </div>

    <div class="card__bottom">
        <div class="card__row">
        </div>
        <div class="card__row">
            <%= f.submit 'POSTER', class: 'button__small button__info' %>
        </div>
    </div>
</div>
<% end %>

app/views/idioms/_comments_list.html.erb
    <% @idiom.comments.each do |comment|%>
<div class="card">
            <div class="right">
                <%= image_tag comment.user.avatar, class: 'pic-avatar-com' %>
                Par&nbsp;<b><%=comment.user.alias%></b>, le&nbsp;<%=comment.created_at.strftime("%d")%>&nbsp;<%=comment.created_at.strftime("%b.")%>&nbsp;<%=comment.created_at.strftime("%Y")%>
            </div>
    <div class="show__body">
        <%=comment.body%>
    </div>
        <div class="card__bottom">
            <div class="show__links">
                <% if current_user != nil && current_user.is_admin? %>
                    <%= link_to 'Supprimer', idiom_comment_path(@idiom.id, comment.id), method: 'DELETE' %>&nbsp;/&nbsp;
                    <%= link_to 'Modérer', edit_idiom_comment_path(@idiom.id, comment.id)%><br>
                <% end %>
                <% if current_user != nil && comment.user == current_user && !current_user.is_admin? %>
                    <%= link_to 'Supprimer', idiom_comment_path(@idiom.id, comment.id), method: 'DELETE' %>&nbsp;/&nbsp;
                    <%= link_to 'Modifier', edit_idiom_comment_path(@idiom.id, comment.id) %><br>
                <% end %>
            </div>
        </div>
        </div> 
    <%end%>

app/views/idioms/_edit_form.html.erb
<%= form_with model: @idiom, url: idiom_path(@idiom.id), method: :patch, local: true do |f|%>
<div class="profile__title profile__title--bg-color-1">
  <h2 class="center">Éditer mon expression</h2>
</div>
<div class="form" style="height: 88vh;">
  <div class="form__content center">
    <p>Un mot en <b>franglais</b> que tu entends souvent et qui t'agace ?</p> 
    <div class="field">
    <%= f.text_field :title_en, autofocus: true, autocomplete: "title_en", class: "form__control" %>
    </div>

    <div class="field">
    <%= f.text_field :title_fr, autofocus: true, autocomplete: "title_fr", class: "form__control" %>
    </div>
    <p>N'hésite pas à partager plus sur ce mot: son <b>origine</b>, sa <b>définition</b>, le pourquoi du comment de son <b>usage</b>...</p>
    <div class="field">
    <%= f.text_field :body, autofocus: true, autocomplete: "body", class: "form__control" %>
    </div>
    <p> Et à ajouter quelques <b>exemples</b> d'utilisation bien tournés.</p>
    <div class="field">
    <%= f.text_field :example_fr, autofocus: true, autocomplete: "example_fr", class: "form__control" %>
    </div>

    <div class="field">
    <%= f.text_field :example_en, autofocus: true, autocomplete: "example_en", class: "form__control" %>
    </div>
    <p> Pour finir, un peu de <b>grammaire</b>.</p>
  <div class="row">
    <div class="col-3">
      <%= f.label :grammatical_type, "Verbe" %>
      <%= f.radio_button :grammatical_type, "Verbe" %>
    </div>
    <div class="col-3">
      <%= f.label :grammatical_type, "Expression" %>
      <%= f.radio_button :grammatical_type, "Expression" %>
    </div>
    <div class="col-3">
      <%= f.label :grammatical_type, "Adjectif" %>
      <%= f.radio_button :grammatical_type, "Adjectif" %>
    </div>
    <div class="col-3">
      <%= f.label :grammatical_type, "Nom" %>
      <%= f.radio_button :grammatical_type, "Nom" %>
    </div>
    </div>

    <div class="right form__button">
      <%= f.submit "Mettre à jour", class: 'button__normal button__info' %>
    </div>
  <% end %>

app/views/idioms/_like.html.erb
<div style="float: left;">
  <% pre_like = idiom.likes.find { |like| like.user_id == current_user.id} rescue nil %>
    <% if pre_like %>
      <%= button_to idiom_like_path(idiom, pre_like), method: :delete, class: "button__likes--index" do %>
        <span style="font-size: 16px;"><%= idiom.likes.count %></span>
        <%= render partial: "svgs/like.html.erb" %>
      <% end %>
    <% else %>
      <%= button_to idiom_likes_path(idiom), method: :post, class: "button__likes--index" do %>
        <span style="font-size: 16px;"><%= idiom.likes.count %></span>
        <%= render partial: "svgs/liketwo.html.erb" %>
      <% end %>
    <% end %>
</div>

app/views/idioms/_new_form.html.erb
<%= form_for(:idioms, url:(idioms_path), action: "create", method: :post) do |f| %>
<div class="form--new">
  <div class="form__content--new center">
    <h4 class="center">Toutes les expressions du <b>S</b>L<b>A</b>F<b>!</b> ont été proposées par nos utilisateurs, à <b>toi</b> de jouer !</h4>
    <p>Un mot en <b>franglais</b> que tu entends souvent et qui t'agace ?</p> 
    <p>C'est l'occasion de le partager à nos camarades !</p>
    <div>
      <%= f.text_area :title_en, autofocus: true, autocomplete: "title_en", class: "form__control--new", placeholder: 'Mot en franglais (max 50 carac.)' %>
    </div>
    <div>
      <%= f.text_area :title_fr, autofocus: true, autocomplete: "title_fr", class: "form__control--new", placeholder: 'Mot en beau français (max 50 carac.)' %>
    </div>
      <p> Un peu de <b>grammaire</b>..</p>
    <div class="row">
    <div class="col-3">
      <%= f.label :grammatical_type, "Verbe" %>
      <%= f.radio_button :grammatical_type, "Verbe" %>
    </div>
    <div class="col-3">
      <%= f.label :grammatical_type, "Expression" %>
      <%= f.radio_button :grammatical_type, "Expression" %>
    </div>
    <div class="col-3">
      <%= f.label :grammatical_type, "Adjectif" %>
      <%= f.radio_button :grammatical_type, "Adjectif" %>
    </div>
    <div class="col-3">
      <%= f.label :grammatical_type, "Nom" %>
      <%= f.radio_button :grammatical_type, "Nom" %>
    </div>
    </div>
      <p>N'hésite pas à partager plus sur ce mot: son <b>origine</b>, sa <b>définition</b>, le pourquoi du comment de son <b>usage</b>...</p>
      <i>Exemple : Faire sens est la traduction littérale de l'expression 'to make sense'. Faire sens n'a pas de sens, un comble."</i>
    <div>
      <%= f.text_area :body, autofocus: true, autocomplete: "body", class: "form__control--new", placeholder: "Explication (15 - 300 carac.)"%>
    </div>
      <p> Et à ajouter quelques <b>exemples</b> d'utilisation bien tournés.</p>
    <div>
      <%= f.text_area :example_en, autofocus: true, autocomplete: "example", class: "form__control--new", placeholder: "Exemple d'utilisation en franglais (15 - 200 carac.)" %>
    </div>
      <p> PS : un peu d'<b>h</b>umour ne fait jamais de mal.</p>
    <div>
      <%= f.text_area :example_fr, autofocus: true, autocomplete: "example", class: "form__control--new", placeholder: "Exemple d'utilisation en français (15 - 200 carac.)" %>
    </div>
    <div class="right form__button">
      <%= f.submit "Soumettre", class: 'button__normal button__info' %>
    </div>
</div>
</div>
<% end %>

app/views/idioms/_show.html.erb
<div class="center show__title">
        <h1><b style="font-weight: 800;font-family: 'Fraunces'"><%= @idiom.title_en.capitalize %></b><span>&nbsp;&nbsp;<%= @idiom.grammatical_type.capitalize[0..2] %>.</span><br><span class="card__title--second" style="font-size: 32px;font-family: 'Fraunces'"><%= @idiom.title_fr.capitalize %></span></h1><br>
</div>

<div class="card__body">
    <p><%=@idiom.body%><p>
    <i>"<%=@idiom.example_en%>"</i>
    <p><i>"<%=@idiom.example_fr%>"</i><p>
</div>
<div class="right">
    <span>Une expression proposée par <b><%=link_to "#{@idiom.user.alias}", user_idioms_path(@idiom.user.id) %></b></span>
</div>

app/views/idioms/_signin_signout.html.erb
<div class="card">
	<div class="center">
		<span class="opinion">Envie de donner ton avis ?</span>
	</div>
	<div class="signin__buttons">
		<div>
      <%= link_to "S'INSCRIRE", new_user_registration_path, class: 'button__normal button__info--bis' %>
		</div>
		<div>
			<%= link_to "SE CONNECTER", new_user_session_path, class: 'button__normal--signin button__info--bis' %>
		</div>
	</div>
</div>

app/views/idioms/_unlike.html.erb
<div style="float: left;">
  <% pre_unlike = idiom.unlikes.find { |unlike| unlike.user_id == current_user.id} rescue nil %>
  <% if pre_unlike %>
    <%= button_to idiom_unlike_path(idiom, pre_unlike), method: :delete, class: "button__likes--index button__info--index" do %>
    <span style="font-size: 16px;"><%= idiom.unlikes.count %></span>
      <%= render partial: "svgs/unlike.html.erb" %>
    <% end %>
  <% else %>
    <%= button_to idiom_unlikes_path(idiom), method: :post, class: "button__likes--index button__info--index" do %>
    <span style="font-size: 16px;"><%= idiom.unlikes.count %></span>
    <%= render partial: "svgs/unliketwo.html.erb" %>
    <% end %>
<% end %>
</div>

app/views/idioms/edit.html.erb
<%= render 'edit_form' %>

app/views/idioms/index.html.erb
<% if params[:user_id].nil? %>
<%= render 'cards' %>
<% else %>
<div class="profile__title profile__title--bg-color-1">
  <h1>Les expressions de <%= @user.alias %> </h1>
  <%= link_to "Toutes les expressions", idioms_path, class: 'button__normal button__info' %>
</div>
<%= render 'cards' %>
<% end %>

app/views/idioms/new.html.erb
<div class="profile__title profile__title--bg-color-1">
  <h2 class="center">Ajouter une expression</h2>
</div>
<%= render 'new_form' %>

app/views/idioms/show.html.erb
<div class="card">
    <div class="card__button__bottom--admin">
        <% if current_user != nil && (@idiom.comments == current_user || current_user.admin == true) %>
            <%= link_to "Éditer", edit_idiom_path(@idiom.id), class: "button__normal button__info" if @idiom.user == current_user %>
            <%= link_to "Supprimer", idiom_path(@idiom.id), :method => 'DELETE', :data => {:confirm => 'Sûr ?'}, class: "button__normal--admin button__danger" if (@idiom.user == current_user && @idiom.validated?)%>
        <% end %>
    </div>
<%= render 'show'%>
    <div class="card__bottom--profile">
        <div class="card__likes">
            <%= render :partial => "like", :locals => { :idiom => @idiom } %>
            <%= render :partial => "unlike", :locals => { :idiom => @idiom } %>
        </div>
        <div><%= social_share_button_tag("On ne dit pas #{@idiom.title_en} mais #{@idiom.title_fr} ! Merci le @SLAF_FR") %></div>
    </div>
</div>
<%= render 'comments_list' if @idiom.comments.length > 0 %>
<%= render 'comments_form' if current_user != nil %>
<%= render 'signin_signout' if current_user == nil %>