config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  resources :idioms do
    resources :comments
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  resources :users do
    resources :idioms, only: [:index]
  end
  resources :idioms do
    resources :likes
    resources :unlikes
  end

  ### Admin

  resources :admin, only: [:index]
  namespace :admin do
    root 'admin#index'
    resources :user
    resources :idiom
    resources :comment
  end
end

app/models/idiom.rb
class Idiom < ApplicationRecord
  before_create :default_likes
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :unlikes, dependent: :destroy

  validates :title_en, presence: true, length: { minimum: 2, maximum: 50 }
  validates :title_fr, presence: true, length: { minimum: 2, maximum: 50 }
  validates :grammatical_type, presence: true
  validates :body, presence: true, length: { minimum: 15, maximum: 300 }
  validates :example_fr, presence: true, length: { minimum: 15, maximum: 200 }
  validates :example_en, presence: true, length: { minimum: 15, maximum: 200 }
  validates :user, presence: true

  def self.search_by(search)
    @all_letters = [*'A'..'Z']
    if search.blank?
      all
    elsif search == 'top'
      order('likes_count DESC')
    elsif @all_letters.include?(search)
      where('title_en ILIKE ?', "#{search}%")
    else
      where('title_en ILIKE ?', "%#{search}%")
    end
  end

  def default_likes
    self.likes_count = 0
  end
end

app/controllers/admin/idiom_controller.rb
module Admin
  class IdiomController < ApplicationController
    def show
      @idiom = Idiom.find(params[:id])
    end

    def index
      @idioms = Idiom.all.sort_by(&:created_at).reverse
    end

    def edit
      @idiom = Idiom.find(params[:id])
    end

    def update
      @idiom = Idiom.find(params[:id])
      @idiom.update(validated: params[:submit])
      redirect_to admin_idiom_index_path, success: 'Édition validé !'
    end

    def destroy
      Idiom.find(params[:id]).destroy
      redirect_to admin_idiom_index_path, success: 'Expression supprimée avec succès !'
    end
  end
end

app/controllers/idioms_controller.rb
class IdiomsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def show
    @idiom = Idiom.find(params[:id])
  end

def index
  @index_idioms = Idiom.where(validated: true)
  if params[:user_id].nil?
    @idioms_ = @index_idioms.search_by(params[:search])
  else
    @user = User.find(params[:user_id])
    @idioms_ = @index_idioms.where(user: @user)
  end
  @pagy, @idioms = pagy(@idioms_.order(created_at: :desc))
end

  def new
  end

  def create
    @idiom = Idiom.create(
      title_en: params[:idioms][:title_en],
      title_fr: params[:idioms][:title_fr],
      grammatical_type: params[:idioms][:grammatical_type],
      body: params[:idioms][:body],
      example_fr: params[:idioms][:example_fr],
      example_en: params[:idioms][:example_en],
      user: current_user
    )

    if @idiom.save
      flash[:success] = 'Ton expression est en cours de validation !'
      redirect_to idiom_path(@idiom.id)
    else
      flash.now[:error] = @idiom.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    if current_user.admin == true || current_user == @idiom.user
      @idiom = Idiom.find(params[:id])
    else
      redirect_to idiom_path
    end
  end

  def update
    @idiom = Idiom.find(params[:id])
    if @idiom.update(
      title_en: params[:idiom][:title_en],
      title_fr: params[:idiom][:title_fr],
      grammatical_type: params[:idiom][:grammatical_type],
      body: params[:idiom][:body],
      example_fr: params[:idiom][:example_fr],
      example_en: params[:idiom][:example_en],
      user: current_user
    )
      flash[:notice] = 'Édition réussie !'
      redirect_to idiom_path(@idiom.id)
    else
      flash.now[:error] = @idiom.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @idiom = Idiom.find(params[:id])
    @idiom.destroy
    redirect_back(fallback_location: idioms_path)
  end

end

app/helpers/admin/idiom_helper.rb
module Admin
  module IdiomHelper
  end
end

app/helpers/idioms_helper.rb
module IdiomsHelper
end

app/views/admin/idiom/_all_expressions.html.erb
<% @idioms.each do |idiom| %>
    <h3>Expression numéro <%=idiom.id%><h3>
    <p><%=idiom.title_fr%></p>
    <p><%=idiom.title_en%></p>
    <p>Validation : <%= idiom.validated %></p>
    <%= link_to 'Détails & Actions', admin_idiom_path(idiom.id), class: "button__normal button__success"%>
<% end %>

app/views/admin/idiom/_validate_expressions.html.erb
<% @idioms.each do |idiom| %>
    <%if idiom.validated == false%>
    <h3>Expression numéro <%=idiom.id%><h3>
    <p><%=idiom.title_fr%></p>
    <p><%=idiom.title_en%></p>
    <%= link_to 'Détails & Actions', admin_idiom_path(idiom.id), class: "button__normal button__success"%>
    <%end%>
<% end %>

app/views/admin/idiom/edit.html.erb
<%= render 'idioms/edit_form' %>

app/views/admin/idiom/index.html.erb
<div class="container">
<h1>Tableau de bord - Les Expressions</h1>
<%= link_to "Retourner au tableau de bord Admin", admin_root_path, class: "button__normal button__info" %>

<h2>Expressions à valider</h2>
<%= render 'validate_expressions' %>

<h2>Toutes les expressions</h2>
<%= render 'all_expressions' %>
</div>

app/views/admin/idiom/show.html.erb
<div class="profile__title profile__title--bg-color-1">
    <h1>Expression <%=@idiom.id %></h1>
    <%= link_to "Retour", admin_root_path, class: 'button__normal button__info' %>
</div>
<div class="card">
    <%= render 'idioms/show'%>
    <div class="card__button__bottom">
        <%= link_to "Éditer", edit_admin_idiom_path(@idiom.id), class: "button__normal button__info" %>
        <%= link_to "Supprimer", admin_idiom_path(@idiom.id), :method => 'DELETE', :data => {:confirm => 'Sûr ?'}, class: "button__normal button__danger" %>
        <% if @idiom.validated == false %>
            <%= link_to "Valider", admin_idiom_path(@idiom.id, submit: 'true'), method: 'patch', class: "button__normal button__success" %>
            <%= link_to "Refuser", admin_idiom_path(@idiom.id, submit: 'false'), method: 'patch', class: "button__normal button__danger" %>
        <% end %>
    </div>
</div>